"""venues, swimmers, team profiles, meet venue fk, tri meet type

Revision ID: 54c829fa8854
Revises: 165d8424beea
Create Date: 2026-08-26 23:08:28.679367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c829fa8854'
down_revision: Union[str, Sequence[str], None] = '165d8424beea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic's autogenerate doesn't detect new enum values on a Postgres
    # native enum type (only table/column diffs) — added by hand. Must run
    # outside the migration's transaction: Postgres won't let a new enum
    # value be used in the same transaction that adds it, and since this
    # value isn't used until later, autocommit here just avoids any
    # ambiguity rather than being strictly required.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE meet_type ADD VALUE IF NOT EXISTS 'tri'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('course_type', sa.Enum('scy', 'scm', 'lcm', name='course_type'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swimmers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('class_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swimmers_team_id'), 'swimmers', ['team_id'], unique=False)
    op.add_column('markets', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'markets', 'teams', ['team_id'], ['id'])
    op.add_column('meets', sa.Column('venue_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'meets', 'venues', ['venue_id'], ['id'])
    op.drop_column('meets', 'venue')
    op.add_column('teams', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('teams', sa.Column('home_venue_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'teams', 'venues', ['home_venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres has no DROP VALUE for enums — removing 'tri' would require
    # recreating the type. Not worth it for a downgrade path; if this ever
    # needs reverting, leaving 'tri' as an unused enum value is harmless.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'home_venue_id')
    op.drop_column('teams', 'location')
    op.add_column('meets', sa.Column('venue', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'meets', type_='foreignkey')
    op.drop_column('meets', 'venue_id')
    op.drop_constraint(None, 'markets', type_='foreignkey')
    op.drop_column('markets', 'team_id')
    op.drop_index(op.f('ix_swimmers_team_id'), table_name='swimmers')
    op.drop_table('swimmers')
    op.drop_table('venues')
    # ### end Alembic commands ###
