import type { TeamConference, TeamDivision } from "./api/types";

export const TEAM_DIVISIONS: TeamDivision[] = ["D1", "D2", "D3"];

export const TEAM_CONFERENCES: TeamConference[] = [
  "America East Conference", "American Athletic Conference", "Atlantic 10 Conference", "Atlantic Coast Conference", "Atlantic Sun Conference", "Big 12 Conference", "Big East Conference", "Big Ten Conference", "Big West Conference", "Coastal Athletic Association", "Horizon League", "Ivy League", "Metro Atlantic Athletic Conference", "Mid-American Conference", "Missouri Valley Conference", "Mountain West Conference", "Northeast Conference", "Pac-12 Conference", "Patriot League", "Southeastern Conference", "Southern Conference", "Summit League", "Sun Belt Conference", "West Coast Conference", "Mountain Pacific Sports Federation", "Metropolitan Swimming Conference",
  "California Collegiate Athletic Association", "Central Atlantic Collegiate Conference", "Conference Carolinas", "East Coast Conference", "Great Lakes Intercollegiate Athletic Conference", "Great Lakes Valley Conference", "Great Midwest Athletic Conference", "Lone Star Conference", "Mountain East Conference", "Northeast-10 Conference", "Northern Sun Intercollegiate Conference", "Peach Belt Conference", "Pennsylvania State Athletic Conference", "Rocky Mountain Athletic Conference", "South Atlantic Conference", "Sunshine State Conference", "Appalachian Swimming Conference", "New South Intercollegiate Swim Conference", "Pacific Coast Swim Conference",
  "Allegheny Mountain Collegiate Conference", "American Rivers Conference", "American Southwest Conference", "Atlantic East Conference", "Centennial Conference", "City University of New York Athletic Conference", "Coast to Coast Athletic Conference", "College Conference of Illinois and Wisconsin", "Collegiate Conference of the South", "Conference of New England", "Empire 8", "Great Northeast Athletic Conference", "Heartland Collegiate Athletic Conference", "Landmark Conference", "Liberty League", "Little East Conference", "Michigan Intercollegiate Athletic Association", "Middle Atlantic Conferences", "Midwest Conference", "Minnesota Intercollegiate Athletic Conference", "New England Collegiate Conference", "New England Small College Athletic Conference", "New England Women's and Men's Athletic Conference", "New Jersey Athletic Conference", "North Atlantic Conference", "North Coast Athletic Conference", "Northwest Conference", "Ohio Athletic Conference", "Old Dominion Athletic Conference", "Presidents' Athletic Conference", "Skyline Conference", "Southern Athletic Association", "Southern California Intercollegiate Athletic Conference", "Southern Collegiate Athletic Conference", "State University of New York Athletic Conference", "United East Conference", "University Athletic Association", "USA South Athletic Conference", "Wisconsin Intercollegiate Athletic Conference",
];
